### ISSUE TITLE
enhancement: Portfolio.go Build TODO

### ISSUE THREAD

**Issue by jakeschurch** [jakeschurch/porttools#3]
- [x] struct: Market Portfolio
- [ ] interface: for market portfolio/portfolio structs
- [x] method: add new securities/holdings (go channel/fan-in func)  
- [ ] method: update holding data
- [x] method: holding transaction functions
